### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by olhor** [Jeija/bluefluff#23]
This what happens after running `node fluffd.js`
`
info: Discovered Furby: <furby_mac>
error: Error while connecting: Error: Connection Rejected due to Limited Resources (0xd)
`
Any ideas?

**Comment by Jeija** [comment]
See https://github.com/Jeija/bluefluff/issues/15
If you have the Intel AC 7260 wireless card, that should explain your problem.

**Comment by olhor** [comment]
Thanks for quick response. I do not know how did I miss it from 'noble' docs... I checked them on how to write sample test app. 
If this can solve the problem:

> You need to stop scanning before trying to connect in order to solve this issue.

and I am able to get my BT adapter info from 'noble' I will try to make a PR to the repo fixing the issue.
