### ISSUE TITLE
Injected audio files not playing on Furby

### ISSUE THREAD

**Issue by doanho** [Jeija/bluefluff#27]
Hey, Jeija, 

Thank you very much for making such interesting project. 

I have managed to flash and activate custom DLC file, however my injected audio files are not playing. I am converting via the Gadget Audio Batch converter with 16Khz WAV input as described in your project. Output is .a18 file with 16000 bps. 

I have also tried all combinations of offsets.

Do you have any idea what can be wrong? What exact procedure did you use when you injected the songs? 

I would appreciate any kind of help. Thanks.

**Comment by Jeija** [comment]
What exactly happens? Do the files not play at all, is there silence instead or just weird noises? Does the regular sound play?
Recently, Context Information Security did a much better job at understanding the DLC file structure, maybe these tools here can help you inject your own files: https://github.com/ctxis/Furby

**Comment by doanho** [comment]
The files do not play at all, but the regular sounds play. Do you have any ideas?

I will surely check out the tools. 

Thank you very much.

**Comment by doanho** [comment]
I have found out that the audio files are not being injected into the DLC file. OUTFILE and TARGET files have the same size. 

Here is the attachment with the inject_binary I am using.  [util.zip](https://github.com/Jeija/bluefluff/files/1601065/util.zip)

The sounds 
[sounds.zip](https://github.com/Jeija/bluefluff/files/1601524/sounds.zip)

Can you please check it? 

Thank you very much.
