### ISSUE TITLE
Fluffd crashes on debug

### ISSUE THREAD

**Issue by tluxton** [Jeija/bluefluff#56]
I can connect to fluffd.js fine and run commands through Preprogrammed Actions in fluffd-client to Furby fine. But when I click Send button on 'Debug Screen' I get an error pop up in browser 'This page says: error: TypeError: callback is not a function'. And in command prompt I see the same error but then message: 'Unknown Peripheral edd5da2184e2'  several times before getting the line: 'MaxlistenersExceededwarning: Possible Eventemitter memory leak detected. 11 write listeners added  to [characteristic]. Use emitter.setMaxListeners() to increase limit. Meahwhile Furby mutter some crap about "Why so Soon" and shuts down. 

Would appreciate a step in the right direction as this has taken ages to get to this stage! I'm guessing Im doing something stupid with not using debug mode correctly?

Cheers
 
![image](https://user-images.githubusercontent.com/47230294/113493893-e8163f00-9526-11eb-901d-91db3c559660.png)

![image](https://user-images.githubusercontent.com/47230294/113493933-46432200-9527-11eb-982a-676bb88b761c.png)
![image](https://user-images.githubusercontent.com/47230294/113494004-ca95a500-9527-11eb-817c-4e1b7bdae891.png)

**Comment by Jeija** [comment]
Iit seems like you found a bug in the code. I have pushed a fix to this repository (https://github.com/Jeija/bluefluff/commit/42d1338037c645ccef0851b82f72a4180e2cbaee), could you update your local files (or manually edit that single line in fluffaction.js) and see if it works now?

I haven't actually tested the fix with my Furby yet, so let me know in case it doesn't work for you.

**Comment by tluxton** [comment]
awesome thanks it works now! just another question in fluffd-client what format should the Delete DLC command be in? ie something like 75.0.2.6 ?

**Comment by Jeija** [comment]
No, it is the DLC slot number, so something like "0" or "1" or "2" or "3"..., depending on which slot you flashed a DLC to.
The debug eyes provide a hint as to which DLC slots are in use, see https://github.com/Jeija/bluefluff/blob/master/doc/flashdlc.md.
