### ISSUE TITLE
windows version 

### ISSUE THREAD

**Issue by FlorinBoghian** [Jeija/bluefluff#58]
just asking if there is a windows version becouse i dont have access to a linux or a mac system.

**Comment by Jeija** [comment]
Some people have got it to work on windows, but it is going to be a lot more complicated and I can't really help with it, see https://github.com/Jeija/bluefluff/issues/1
Maybe you could try https://github.com/pdjstone/furby-web-bluetooth instead?

**Comment by FlorinBoghian** [comment]
thanks
