### ISSUE TITLE
Where should i go from "node fluffd.js"

### ISSUE THREAD

**Issue by psychicspectre** [Jeija/bluefluff#67]
When i try use the above command, nothing happens? 
![image](https://github.com/user-attachments/assets/1544beef-a515-4d6f-a64f-6d0c39a41268)
I cant type in the terminal after i send the command, does anyone have any ideas? Thanks. :)

**Comment by Jeija** [comment]
Just follow [these instructions](https://github.com/Jeija/bluefluff?tab=readme-ov-file#sending-commands-using-fluffd-client):

> You can now open `fluffd-client/index.html` in your favorite web browser to take control of Furby Connect. Most menu items should be self-explanatory. See [the DLC flashing documentation](doc/flashdlc.md) for information on DLC-related commands

So, using your file manager, open the `fluffd-client` folder and open `index.html` in your web browser.

**Comment by psychicspectre** [comment]
I will try that (in the morning) and get back to you, thank you so much!
